-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TRIGGER gen_versionId BEFORE INSERT OR UPDATE ON public.doc_item
--     FOR EACH ROW EXECUTE FUNCTION gen_versionId();
